import 'server-only'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { AwsClient } from 'aws4fetch'
import { env } from '@/lib/env'
import { AppError, ProviderNotConfiguredError } from '@/lib/errors'

/**
 * File storage for uploaded media (product images, review photos).
 *
 * - local: files under UPLOAD_DIR, served by the /uploads route. For
 *   development and single-server installs; production config rejects it
 *   unless explicitly allowed, because serverless disks are not durable.
 * - s3: any S3-compatible bucket (AWS S3, Cloudflare R2, …) signed with
 *   SigV4; files are served from STORAGE_PUBLIC_BASE_URL.
 *
 * Keys are generated by the server (content hashes), never taken from users.
 */

export interface StoredObject {
  key: string
  url: string
}

export interface StorageProvider {
  readonly name: 'local' | 's3'
  put(key: string, body: Uint8Array, contentType: string): Promise<StoredObject>
  delete(key: string): Promise<void>
}

const KEY_PATTERN =
  /^[a-z0-9][a-z0-9-]*(?:\/[a-z0-9][a-z0-9_-]*)*\/[a-z0-9_-]+\.(?:webp|jpg|png|avif)$/

/** Server-generated keys only: lowercase segments, a known image extension, no traversal. */
export function assertSafeKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.includes('..') || key.length > 300) {
    throw new AppError('BAD_REQUEST', 'Invalid storage key', { status: 400 })
  }
}

export const IMAGE_CONTENT_TYPES: Record<string, string> = {
  webp: 'image/webp',
  jpg: 'image/jpeg',
  png: 'image/png',
  avif: 'image/avif',
}

// Runtime-only paths (uploads live outside the build): told to the bundler so it
// does not trace the whole project into the server output.
export function localUploadRoot(): string {
  return path.resolve(/* turbopackIgnore: true */ process.cwd(), env().UPLOAD_DIR)
}

/** Absolute path of a key inside the upload root, or null if it would escape it. */
export function localPathFor(key: string): string | null {
  const root = localUploadRoot()
  const resolved = path.resolve(/* turbopackIgnore: true */ root, key)
  return resolved.startsWith(root + path.sep) ? resolved : null
}

export class LocalStorageProvider implements StorageProvider {
  readonly name = 'local' as const

  async put(key: string, body: Uint8Array, _contentType: string): Promise<StoredObject> {
    assertSafeKey(key)
    const target = localPathFor(key)
    if (!target) throw new AppError('BAD_REQUEST', 'Invalid storage key', { status: 400 })
    await mkdir(path.dirname(target), { recursive: true })
    await writeFile(target, body, { mode: 0o644 })
    return { key, url: `/uploads/${key}` }
  }

  async delete(key: string): Promise<void> {
    assertSafeKey(key)
    const target = localPathFor(key)
    if (target) await rm(target, { force: true })
  }

  /** Read a stored file (used by the /uploads route). */
  async read(key: string): Promise<Buffer | null> {
    const target = localPathFor(key)
    if (!target) return null
    try {
      return await readFile(target)
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null
      throw error
    }
  }
}

export class S3StorageProvider implements StorageProvider {
  readonly name = 's3' as const
  private readonly client: AwsClient

  constructor(
    private readonly config: {
      bucket: string
      region: string
      endpoint: string | undefined
      accessKeyId: string
      secretAccessKey: string
      publicBaseUrl: string
    },
  ) {
    this.client = new AwsClient({
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
      region: config.region,
      service: 's3',
    })
  }

  private objectUrl(key: string): string {
    const endpoint = (
      this.config.endpoint ?? `https://s3.${this.config.region}.amazonaws.com`
    ).replace(/\/$/, '')
    return `${endpoint}/${encodeURIComponent(this.config.bucket)}/${key}`
  }

  async put(key: string, body: Uint8Array, contentType: string): Promise<StoredObject> {
    assertSafeKey(key)
    // Copy into a plain ArrayBuffer-backed view (what fetch's BodyInit accepts).
    const payload = new Uint8Array(body.byteLength)
    payload.set(body)
    const response = await this.client.fetch(this.objectUrl(key), {
      method: 'PUT',
      body: payload,
      headers: {
        'content-type': contentType,
        // Keys are content hashes, so an object never changes.
        'cache-control': 'public, max-age=31536000, immutable',
      },
    })
    if (!response.ok) {
      throw new AppError('PROVIDER_ERROR', `Storage upload failed (${response.status})`, {
        status: 502,
      })
    }
    return { key, url: `${this.config.publicBaseUrl.replace(/\/$/, '')}/${key}` }
  }

  async delete(key: string): Promise<void> {
    assertSafeKey(key)
    const response = await this.client.fetch(this.objectUrl(key), { method: 'DELETE' })
    if (!response.ok && response.status !== 404) {
      throw new AppError('PROVIDER_ERROR', `Storage delete failed (${response.status})`, {
        status: 502,
      })
    }
  }
}

let override: StorageProvider | null = null

export function getStorage(): StorageProvider {
  if (override) return override
  const config = env()
  if (config.STORAGE_PROVIDER === 'local') return new LocalStorageProvider()
  const missing = (
    [
      'STORAGE_BUCKET',
      'STORAGE_REGION',
      'STORAGE_ACCESS_KEY_ID',
      'STORAGE_SECRET_ACCESS_KEY',
      'STORAGE_PUBLIC_BASE_URL',
    ] as const
  ).filter((key) => !config[key])
  if (missing.length > 0) throw new ProviderNotConfiguredError('s3', missing)
  return new S3StorageProvider({
    bucket: config.STORAGE_BUCKET!,
    region: config.STORAGE_REGION!,
    endpoint: config.STORAGE_ENDPOINT,
    accessKeyId: config.STORAGE_ACCESS_KEY_ID!,
    secretAccessKey: config.STORAGE_SECRET_ACCESS_KEY!,
    publicBaseUrl: config.STORAGE_PUBLIC_BASE_URL!,
  })
}

/** Test hook. */
export function setStorage(provider: StorageProvider | null): void {
  override = provider
}
